# -*- coding: utf-8 -*-
"""task 7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/175a1yQlIRoi8OewRPJ8vXRMPxqiNTya7
"""

import sqlite3

conn = sqlite3.connect("sales_data.db")
cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS sales (
    id INTEGER PRIMARY KEY,
    product TEXT,
    quantity INTEGER,
    price REAL
)
""")

sample_data = [
    ("Laptop", 3, 60000),
    ("Mobile", 5, 20000),
    ("Tablet", 4, 15000),
    ("Laptop", 2, 65000),
    ("Mobile", 3, 22000)
]
cursor.executemany("INSERT INTO sales (product, quantity, price) VALUES (?, ?, ?)", sample_data)

conn.commit()
conn.close()

import sqlite3
import pandas as pd
conn = sqlite3.connect("sales_data.db")
query = """
SELECT
    product,
    SUM(quantity) AS total_qty,
    SUM(quantity * price) AS revenue
FROM sales
GROUP BY product
"""
df = pd.read_sql_query(query, conn)
print(df)
conn.close()

import matplotlib.pyplot as plt
df.plot(kind='bar', x='product', y='revenue', legend=False)

plt.title("Sales Revenue by Product")
plt.xlabel("Product")
plt.ylabel("Revenue")
plt.tight_layout()
plt.show()